name: Publish canary

on: issue_comment

jobs:
  pr_commented:
    name: PR commented
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/canary') }}
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: ${{ github.event.issue.number }}
    steps:
      - name: Auth
        uses: actions/create-github-app-token@v1
        id: auth
        with: 
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: PR accepted
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ steps.auth.outputs.token }}
          comment-id: ${{ github.event.comment.id }}
          reactions: heart
      - uses: actions/checkout@v3
        with: 
          ref: ${{ github.head_ref }}
      - id: commit
        uses: prompt/actions-commit-hash@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.NODE_VERSION }}
      - uses: actions/cache@v3
        with:
          path: node_modules
          key: npm-deps-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-deps-${{ hashFiles('package-lock.json') }}
      - name: Setup packages
        run: npm ci
      - name: Publish canary to NPM
        id: canary
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "Publishing from PR: ${{ github.event.issue.number }}. On branch: ${{ github.head_ref }}" 
          npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
          npm version 0.0.0-${{ steps.commit.outputs.short }} --git-tag-version false
          npm publish --tag canary
          echo "version=0.0.0-${{ steps.commit.outputs.short }}" >> "$GITHUB_OUTPUT"
      - name: Comment version to PR
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ steps.auth.outputs.token }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Canary available: `@taskany/bricks@${{ steps.canary.outputs.version }}`
      
        
