name: Publish canary

on: issue_comment

jobs:
  pr_commented:
    name: PR commented
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: PR check
        id: pr
        env:
          PR_NUMBER: ${{ github.event.issue.number }}
        if: ${{ startsWith(github.event.comment.body, '/canary') }}
        run: |
          echo canary request on PR $PR_NUMBER
      - name: Auth
        uses: actions/create-github-app-token@v1
        id: auth
        with: 
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.NODE_VERSION }}
      - uses: actions/cache@v3
        with:
          path: node_modules
          key: npm-deps-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-deps-${{ hashFiles('package-lock.json') }}
      - name: Setup packages
        run: npm ci
      - name: Publish canary to NPM
        id: canary
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          # save version
          # npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
          # npm publish 
          echo publish 0.0.0-$(date +'%Y-%m-%d-%H-%M-%S')
          echo "version=0.0.0-$(date +'%Y-%m-%d-%H-%M-%S')" >> "$GITHUB_OUTPUT"
      - name: Comment version to PR
        env:
          GH_TOKEN: ${{ steps.auth.outputs.token }}
          PR_NUMBER: ${{ github.event.issue.number }}
          VERSION: ${{ steps.canary.outputs.version }}
        run: |
          gh pr comment $PR_NUMBER --body "Canary available: \`@taskany/bricks@$VERSION\`"
        
