name: Publish Release

on:
  pull_request_target:
    types:
      - closed
    paths:
      - '.release_notes/**'

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    name: Publish Release
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: taskany-inc/release/.github/workflows/checkout.yml@main
      - name: Publish to NPM
        uses: taskany-inc/release/.github/workflows/npm_publish.yml@main
      - name: GitHub Release
        uses: taskany-inc/release/.github/workflows/gh_release.yml@main
