name: Publish

on:
  pull_request_target:
    types:
      - closed
    paths:
      - '.release_notes/**'

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    name: Publish Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18.12.0

      - name: Cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: npm-deps-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-deps-${{ hashFiles('package-lock.json') }}

      - name: Setup packages
        run: npm ci

      - name: Publush to NPM
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
          npm publish

      - name: Release Tag
        run: |
          git config --global user.email "sheep@taskany.org"
          git config --global user.name "Taskany Sheep"
          git tag v$(cat version)
          git push --no-verify origin --tags

      - name: GitHub Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create v$(cat version) --title "Release $(cat version)" -F .release_notes/$(cat version).md
