name: Publish

on:
  pull_request_target:
    types:
      - closed
    paths:
      - '.release_notes/**'

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    name: Publish Release
    uses: taskany-inc/release/.github/workflows/publish.yml@main
