name: Publish Release

on:
  push:
    branches:
      - main
      
jobs:
  npm_publish:
    if: github.event.pull_request.merged == true
    uses: taskany-inc/release/.github/workflows/npm_publish.yml@main
    secrets: inherit
