name: Publish Release

on:
  workflow_dispatch:
  pull_request_target:
    types:
      - closed
      
jobs:
  npm_publish:
    uses: taskany-inc/release/.github/workflows/npm_publish.yml@main
    secrets: inherit
